### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' for channel

### ISSUE THREAD

**Issue by kprdev** [kprdev/Dububot#3]
> future: <Task finished coro=<twitch_loop() done, defined at Dububot.py:72> exception=AttributeError("'NoneType' object has no attribute 'get'",)>
> Traceback (most recent call last):
>   File "Dububot.py", line 94, in twitch_loop
>     await client.send_message(channel, content=message, embed=embed)
>   File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 1153, in send_message
>     channel = self.get_channel(data.get('channel_id'))
> AttributeError: 'NoneType' object has no attribute 'get'

**Comment by kprdev** [comment]
Not sure anything can be done about this. The 'channel' value was used already to post messages successfully so not sure why it became `None`. We'll see if it happens again.
